---
abstract: 'chomp and chop replacements that pass the changed value(s) back'
author:
  - 'Michael Jemmeson <mjemmeson@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Chompp
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Text::Chompp:
    file: lib/Text/Chompp.pm
    version: 0.001
requires:
  Exporter: 0
  base: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/mjemmeson/text-chompp/issues
  homepage: https://metacpan.org/release/Text-Chompp
  repository: git://github.com/mjemmeson/text-chompp.git
version: 0.001
